global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'email'
  
receivers:
- name: 'email'
  email_configs:
  - to: 'polcafumikaxd@outlook.com'
    from: 'testmailtrap@example.com'
    smarthost: sandbox.smtp.mailtrap.io:25
    auth_username: 'c81cbd36605b24'
    auth_identity: 'c81cbd36605b24'
    auth_password: '976f26cbd2e6c8'
